%variable = linspace(0, 1, 20);
% energy of particles in MeV
variable = 10:5:15;
% theta in vertical direction (polarisation)
% in mrad
theta_range = -20:1:20;
% phi in vertical direction (non-polarisation)
phi_range = -20:1:20;
% Based on the input decks runGamma
executecommand = strings(length(variable)*length(theta_range)*length(phi_range),1);
j = 0;
for n = 1:length(variable)
    var = variable(n);
    for i = 1:length(theta_range)
        theta = theta_range(i);
        for k = 1:length(phi_range)
            j = j+1;
            phi = phi_range(k);
            macfname = ['/Users/eg415/GEANT/QED/scripts_profilethetaphi/GammaProfile_' num2str(var, '%03d') 'MeV_' num2str(theta,'%03d') 'mradTheta_' num2str(phi,'%03d') 'mradPhi.mac'];
            outputfname = ['GP_' num2str(var, '%03d') 'MeV_' num2str(theta, '%03d') 'mradT_' num2str(phi, '%03d') 'mradP'];

            inputdeck= ['/run/numberOfThreads 1' char(10),...
                        '/run/initialize' char(10), ...
                        '/vis/open HepRepFile' char(10), ...
                        '/vis/drawVolume' char(10), ...
                        '/vis/scene/add/trajectories smooth' char(10), ...
                        '/vis/scene/endOfEventAction accumulate 10' char(10), ...
                        '/gps/particle gamma' char(10), ...
                        '/gps/pos/centre 0 0 42.5 cm' char(10), ...
                        '/gps/ang/type beam1d' char(10), ...
                        '/gps/ang/sigma_r 0.02 deg' char(10), ...
                        '/gps/pos/type Beam' char(10), ...
                        '/gps/pos/shape Circle' char(10), ...
                        '/gps/pos/sigma_r 0.425 um' char(10), ...
                        '/gps/direction ' num2str(sin(phi/1000),'%d') ' ' num2str(sin(theta/1000)*cos(phi/1000),'%d') ' ' num2str(-cos(theta/1000)*cos(phi/1000),'%d') char(10),...
                        '/gps/ene/type Lin' char(10), ...
                        '/gps/ene/min ' num2str(var) ' MeV' char(10), ...
                        '/gps/ene/max ' num2str(var) ' MeV' char(10), ...
                        '/gps/ene/gradient 0' char(10), ...
                        '/gps/ene/intercept 1' char(10), ...
                        '/B1/histo/setOutputFile ' outputfname char(10), ...
                        '/run/beamOn 10000' char(10),...
                        '/vis/viewer/flush'];

            fid = fopen(macfname, 'w');
            fprintf(fid, inputdeck);
            fclose(fid);


            executecommand{j} =  ['./QED ' macfname ';'];
        end
    end
    %executecommand = [executecommand './QED ' macfname '; python root2mat.py ./data/' outputfname '.root; '];
    %executecommand = [executecommand,...
    %    './QED ' macfname ';'];
end

executecommand_file = 'buffer_thetaphiprofile.txt';
fid = fopen(executecommand_file, 'w');
fprintf(fid,'%s\n', executecommand);
fclose(fid);
%clipboard('copy',executecommand)
